services:
    database:
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        depends_on:
            - database
        networks:
            - db_network
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=wiki-database
            - PMA_PORT=3306
        container_name: wiki-phpmyadmin